### PR TITLE
Bump dbt version

### PR DESCRIPTION
**Pull request by clrcrl**
## Description & motivation
0.18.0 release

## Checklist
- [x] I have verified that these changes work locally
- n/a I have updated the README.md (if applicable)
- n/a I have added tests & descriptions to my models (and macros if applicable)

### CODE REVIEW

**Comment by clrcrl** [comment]
@jtcohen6 —  can you look into this one when you get a chance?

**Comment by jtcohen6** [comment]
Okay, I resolved the confusing error and wound up with another weird one. Here's the gist: `get_relations_by_prefix` is not returning any results in `codegen_integration_tests_bigquery_raw_data`, even though it should. Why?

This is a bug in dbt-utils, and I think it's on me (from refactor to get tests passing in https://github.com/fishtown-analytics/dbt-utils/pull/267). BigQuery needs [this line](https://github.com/fishtown-analytics/dbt-utils/blob/dev/0.7.0/macros/sql/get_tables_by_pattern_sql.sql#L23) to be:
```sql
        from {{adapter.quote(database)}}.{{schema_pattern}}.INFORMATION_SCHEMA.TABLES
```
...sort of. Because information schemas are scoped to the dataset/schema on BQ, not the project/database, we don't really have a way of searching for a schema _pattern_ as we do on the other databases. The utils test passes because we're not using a custom schema there, but we are here (`raw_data`).

**Comment by clrcrl** [comment]
Resolved that issue [here](https://github.com/fishtown-analytics/dbt-utils/pull/275)

**Comment by clrcrl** [comment]
(Waiting for hub 0.6.1 release before kicking off again)

**Comment by jtcohen6** [comment]
I just made a mess in Circle while trying to find the right workflow to rerun. Looks like this works with utils 0.6.1!

**Comment by clrcrl** [comment]
Removed the commit that added the placeholder model and have bumped the lower range of utils

**Review by jtcohen6 — APPROVED** [review]
LGTM

**Pull request merged**
